version: '3.8'

services:
  backend:
    build: ./backend
    container_name: myson-backend
    ports:
      - "8080:8080"
    restart: on-failure
    env_file:
      - .env
    networks:
      - myson-network

  frontend:
    build:
      context: ./frontend
      args:
        - VITE_API_URL=${VITE_API_URL}
        - VITE_API_BASE_URL=${VITE_API_BASE_URL}
        - VITE_KAKAO_APP_KEY=${VITE_KAKAO_APP_KEY}
    container_name: myson-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - myson-network

networks:
  myson-network:
    driver: bridge
